# Generated by Django 3.2.16 on 2023-04-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_extension_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='user',
        ),
    ]
