# Generated by Django 3.2.16 on 2023-04-19 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_extension_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
