# Generated by Django 3.2.16 on 2023-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230419_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject', to='api.Groups'),
        ),
    ]
