version: '3'

services:
  education_database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./education_pgdata:/var/lib/postgresql/data

  education_app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/education
    environment:
      - DB_HOST=education_database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:9000"
    depends_on:
      - education_database